apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vkiwas8m1-nodejs 
  janus-idp.io/tekton: vkiwas8m1-nodejs
  backstage.io/kubernetes-id: vkiwas8m1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vkiwas8m1-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml